development:
  dialect: mysql
  datasource: root:Aa123456@tcp(localhost:3306)/fzuSE2024?charset=utf8mb4&timeout=10s&parseTime=True
  dir: sql

production:
  dialect: mysql
  datasource: root:Aa123456@tcp(localhost:3306)/fzuSE2024?charset=utf8mb4&timeout=10s&parseTime=True
  dir: sql
  table: migrations